# Generated by Django 3.0.4 on 2020-03-26 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('enterprenuer', 'organization')], default='enterprenuer', max_length=20)),
                ('top_retailer', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('date_joined', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
