# Generated by Django 3.0.4 on 2020-03-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0002_auto_20200326_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='category',
            field=models.CharField(choices=[('org', 'organization'), ('ent', 'enterprenuer')], default='organization', max_length=20),
        ),
    ]
