# Generated by Django 3.0.4 on 2020-03-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0004_retailer_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='pic',
            field=models.ImageField(upload_to='images/%Y/%m/%d'),
        ),
    ]
