# Generated by Django 3.0.4 on 2020-03-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0005_auto_20200326_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailer',
            name='category',
            field=models.CharField(choices=[('organization', 'organization'), ('enterprenuer', 'enterprenuer')], default='organization', max_length=20),
        ),
    ]
