# Generated by Django 3.0.4 on 2020-03-26 11:28

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retailers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('screen_size', models.CharField(max_length=150)),
                ('operating_system', models.CharField(max_length=150)),
                ('model_number', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('batteries', models.CharField(max_length=255)),
                ('main_photo', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='images/%Y/%m/%d'), blank=True, size=None)),
                ('description', models.TextField(blank=True)),
                ('offer', models.BooleanField(default=False)),
                ('date_uploaded', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='retailers.Retailer')),
            ],
        ),
    ]
