# Generated by Django 3.0.4 on 2020-03-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allproducts', '0002_auto_20200326_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recent',
            field=models.BooleanField(default=False),
        ),
    ]
